data modify storage pretty_crafter: found.recipe.result.tag merge from storage pretty_crafter: found.items[].tag

execute if data storage pretty_crafter: found.items[0] run data modify storage pretty_crafter: _.firework set from storage pretty_crafter: found.items[0].id
execute if data storage pretty_crafter: found.items[0] if data storage pretty_crafter: _{firework:"minecraft:white_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 15790320
execute if data storage pretty_crafter: found.items[0] if data storage pretty_crafter: _{firework:"minecraft:orange_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 15435844
execute if data storage pretty_crafter: found.items[0] if data storage pretty_crafter: _{firework:"minecraft:magenta_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 12801229
execute if data storage pretty_crafter: found.items[0] if data storage pretty_crafter: _{firework:"minecraft:light_blue_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 6719955
execute if data storage pretty_crafter: found.items[0] if data storage pretty_crafter: _{firework:"minecraft:yellow_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 14602026
execute if data storage pretty_crafter: found.items[0] if data storage pretty_crafter: _{firework:"minecraft:lime_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 4312372
execute if data storage pretty_crafter: found.items[0] if data storage pretty_crafter: _{firework:"minecraft:pink_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 14188952
execute if data storage pretty_crafter: found.items[0] if data storage pretty_crafter: _{firework:"minecraft:gray_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 4408131
execute if data storage pretty_crafter: found.items[0] if data storage pretty_crafter: _{firework:"minecraft:light_gray_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 11250603
execute if data storage pretty_crafter: found.items[0] if data storage pretty_crafter: _{firework:"minecraft:cyan_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 2651799
execute if data storage pretty_crafter: found.items[0] if data storage pretty_crafter: _{firework:"minecraft:purple_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 8073150
execute if data storage pretty_crafter: found.items[0] if data storage pretty_crafter: _{firework:"minecraft:blue_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 2437522
execute if data storage pretty_crafter: found.items[0] if data storage pretty_crafter: _{firework:"minecraft:brown_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 5320730
execute if data storage pretty_crafter: found.items[0] if data storage pretty_crafter: _{firework:"minecraft:green_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 3887386
execute if data storage pretty_crafter: found.items[0] if data storage pretty_crafter: _{firework:"minecraft:red_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 11743532
execute if data storage pretty_crafter: found.items[0] if data storage pretty_crafter: _{firework:"minecraft:black_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 1973019

execute if data storage pretty_crafter: found.items[1] run data modify storage pretty_crafter: _.firework set from storage pretty_crafter: found.items[1].id
execute if data storage pretty_crafter: found.items[1] if data storage pretty_crafter: _{firework:"minecraft:white_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 15790320
execute if data storage pretty_crafter: found.items[1] if data storage pretty_crafter: _{firework:"minecraft:orange_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 15435844
execute if data storage pretty_crafter: found.items[1] if data storage pretty_crafter: _{firework:"minecraft:magenta_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 12801229
execute if data storage pretty_crafter: found.items[1] if data storage pretty_crafter: _{firework:"minecraft:light_blue_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 6719955
execute if data storage pretty_crafter: found.items[1] if data storage pretty_crafter: _{firework:"minecraft:yellow_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 14602026
execute if data storage pretty_crafter: found.items[1] if data storage pretty_crafter: _{firework:"minecraft:lime_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 4312372
execute if data storage pretty_crafter: found.items[1] if data storage pretty_crafter: _{firework:"minecraft:pink_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 14188952
execute if data storage pretty_crafter: found.items[1] if data storage pretty_crafter: _{firework:"minecraft:gray_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 4408131
execute if data storage pretty_crafter: found.items[1] if data storage pretty_crafter: _{firework:"minecraft:light_gray_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 11250603
execute if data storage pretty_crafter: found.items[1] if data storage pretty_crafter: _{firework:"minecraft:cyan_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 2651799
execute if data storage pretty_crafter: found.items[1] if data storage pretty_crafter: _{firework:"minecraft:purple_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 8073150
execute if data storage pretty_crafter: found.items[1] if data storage pretty_crafter: _{firework:"minecraft:blue_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 2437522
execute if data storage pretty_crafter: found.items[1] if data storage pretty_crafter: _{firework:"minecraft:brown_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 5320730
execute if data storage pretty_crafter: found.items[1] if data storage pretty_crafter: _{firework:"minecraft:green_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 3887386
execute if data storage pretty_crafter: found.items[1] if data storage pretty_crafter: _{firework:"minecraft:red_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 11743532
execute if data storage pretty_crafter: found.items[1] if data storage pretty_crafter: _{firework:"minecraft:black_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 1973019

execute if data storage pretty_crafter: found.items[2] run data modify storage pretty_crafter: _.firework set from storage pretty_crafter: found.items[2].id
execute if data storage pretty_crafter: found.items[2] if data storage pretty_crafter: _{firework:"minecraft:white_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 15790320
execute if data storage pretty_crafter: found.items[2] if data storage pretty_crafter: _{firework:"minecraft:orange_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 15435844
execute if data storage pretty_crafter: found.items[2] if data storage pretty_crafter: _{firework:"minecraft:magenta_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 12801229
execute if data storage pretty_crafter: found.items[2] if data storage pretty_crafter: _{firework:"minecraft:light_blue_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 6719955
execute if data storage pretty_crafter: found.items[2] if data storage pretty_crafter: _{firework:"minecraft:yellow_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 14602026
execute if data storage pretty_crafter: found.items[2] if data storage pretty_crafter: _{firework:"minecraft:lime_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 4312372
execute if data storage pretty_crafter: found.items[2] if data storage pretty_crafter: _{firework:"minecraft:pink_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 14188952
execute if data storage pretty_crafter: found.items[2] if data storage pretty_crafter: _{firework:"minecraft:gray_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 4408131
execute if data storage pretty_crafter: found.items[2] if data storage pretty_crafter: _{firework:"minecraft:light_gray_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 11250603
execute if data storage pretty_crafter: found.items[2] if data storage pretty_crafter: _{firework:"minecraft:cyan_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 2651799
execute if data storage pretty_crafter: found.items[2] if data storage pretty_crafter: _{firework:"minecraft:purple_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 8073150
execute if data storage pretty_crafter: found.items[2] if data storage pretty_crafter: _{firework:"minecraft:blue_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 2437522
execute if data storage pretty_crafter: found.items[2] if data storage pretty_crafter: _{firework:"minecraft:brown_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 5320730
execute if data storage pretty_crafter: found.items[2] if data storage pretty_crafter: _{firework:"minecraft:green_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 3887386
execute if data storage pretty_crafter: found.items[2] if data storage pretty_crafter: _{firework:"minecraft:red_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 11743532
execute if data storage pretty_crafter: found.items[2] if data storage pretty_crafter: _{firework:"minecraft:black_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 1973019

execute if data storage pretty_crafter: found.items[3] run data modify storage pretty_crafter: _.firework set from storage pretty_crafter: found.items[3].id
execute if data storage pretty_crafter: found.items[3] if data storage pretty_crafter: _{firework:"minecraft:white_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 15790320
execute if data storage pretty_crafter: found.items[3] if data storage pretty_crafter: _{firework:"minecraft:orange_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 15435844
execute if data storage pretty_crafter: found.items[3] if data storage pretty_crafter: _{firework:"minecraft:magenta_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 12801229
execute if data storage pretty_crafter: found.items[3] if data storage pretty_crafter: _{firework:"minecraft:light_blue_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 6719955
execute if data storage pretty_crafter: found.items[3] if data storage pretty_crafter: _{firework:"minecraft:yellow_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 14602026
execute if data storage pretty_crafter: found.items[3] if data storage pretty_crafter: _{firework:"minecraft:lime_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 4312372
execute if data storage pretty_crafter: found.items[3] if data storage pretty_crafter: _{firework:"minecraft:pink_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 14188952
execute if data storage pretty_crafter: found.items[3] if data storage pretty_crafter: _{firework:"minecraft:gray_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 4408131
execute if data storage pretty_crafter: found.items[3] if data storage pretty_crafter: _{firework:"minecraft:light_gray_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 11250603
execute if data storage pretty_crafter: found.items[3] if data storage pretty_crafter: _{firework:"minecraft:cyan_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 2651799
execute if data storage pretty_crafter: found.items[3] if data storage pretty_crafter: _{firework:"minecraft:purple_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 8073150
execute if data storage pretty_crafter: found.items[3] if data storage pretty_crafter: _{firework:"minecraft:blue_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 2437522
execute if data storage pretty_crafter: found.items[3] if data storage pretty_crafter: _{firework:"minecraft:brown_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 5320730
execute if data storage pretty_crafter: found.items[3] if data storage pretty_crafter: _{firework:"minecraft:green_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 3887386
execute if data storage pretty_crafter: found.items[3] if data storage pretty_crafter: _{firework:"minecraft:red_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 11743532
execute if data storage pretty_crafter: found.items[3] if data storage pretty_crafter: _{firework:"minecraft:black_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 1973019

execute if data storage pretty_crafter: found.items[4] run data modify storage pretty_crafter: _.firework set from storage pretty_crafter: found.items[4].id
execute if data storage pretty_crafter: found.items[4] if data storage pretty_crafter: _{firework:"minecraft:white_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 15790320
execute if data storage pretty_crafter: found.items[4] if data storage pretty_crafter: _{firework:"minecraft:orange_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 15435844
execute if data storage pretty_crafter: found.items[4] if data storage pretty_crafter: _{firework:"minecraft:magenta_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 12801229
execute if data storage pretty_crafter: found.items[4] if data storage pretty_crafter: _{firework:"minecraft:light_blue_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 6719955
execute if data storage pretty_crafter: found.items[4] if data storage pretty_crafter: _{firework:"minecraft:yellow_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 14602026
execute if data storage pretty_crafter: found.items[4] if data storage pretty_crafter: _{firework:"minecraft:lime_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 4312372
execute if data storage pretty_crafter: found.items[4] if data storage pretty_crafter: _{firework:"minecraft:pink_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 14188952
execute if data storage pretty_crafter: found.items[4] if data storage pretty_crafter: _{firework:"minecraft:gray_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 4408131
execute if data storage pretty_crafter: found.items[4] if data storage pretty_crafter: _{firework:"minecraft:light_gray_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 11250603
execute if data storage pretty_crafter: found.items[4] if data storage pretty_crafter: _{firework:"minecraft:cyan_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 2651799
execute if data storage pretty_crafter: found.items[4] if data storage pretty_crafter: _{firework:"minecraft:purple_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 8073150
execute if data storage pretty_crafter: found.items[4] if data storage pretty_crafter: _{firework:"minecraft:blue_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 2437522
execute if data storage pretty_crafter: found.items[4] if data storage pretty_crafter: _{firework:"minecraft:brown_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 5320730
execute if data storage pretty_crafter: found.items[4] if data storage pretty_crafter: _{firework:"minecraft:green_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 3887386
execute if data storage pretty_crafter: found.items[4] if data storage pretty_crafter: _{firework:"minecraft:red_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 11743532
execute if data storage pretty_crafter: found.items[4] if data storage pretty_crafter: _{firework:"minecraft:black_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 1973019

execute if data storage pretty_crafter: found.items[5] run data modify storage pretty_crafter: _.firework set from storage pretty_crafter: found.items[5].id
execute if data storage pretty_crafter: found.items[5] if data storage pretty_crafter: _{firework:"minecraft:white_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 15790320
execute if data storage pretty_crafter: found.items[5] if data storage pretty_crafter: _{firework:"minecraft:orange_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 15435844
execute if data storage pretty_crafter: found.items[5] if data storage pretty_crafter: _{firework:"minecraft:magenta_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 12801229
execute if data storage pretty_crafter: found.items[5] if data storage pretty_crafter: _{firework:"minecraft:light_blue_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 6719955
execute if data storage pretty_crafter: found.items[5] if data storage pretty_crafter: _{firework:"minecraft:yellow_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 14602026
execute if data storage pretty_crafter: found.items[5] if data storage pretty_crafter: _{firework:"minecraft:lime_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 4312372
execute if data storage pretty_crafter: found.items[5] if data storage pretty_crafter: _{firework:"minecraft:pink_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 14188952
execute if data storage pretty_crafter: found.items[5] if data storage pretty_crafter: _{firework:"minecraft:gray_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 4408131
execute if data storage pretty_crafter: found.items[5] if data storage pretty_crafter: _{firework:"minecraft:light_gray_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 11250603
execute if data storage pretty_crafter: found.items[5] if data storage pretty_crafter: _{firework:"minecraft:cyan_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 2651799
execute if data storage pretty_crafter: found.items[5] if data storage pretty_crafter: _{firework:"minecraft:purple_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 8073150
execute if data storage pretty_crafter: found.items[5] if data storage pretty_crafter: _{firework:"minecraft:blue_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 2437522
execute if data storage pretty_crafter: found.items[5] if data storage pretty_crafter: _{firework:"minecraft:brown_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 5320730
execute if data storage pretty_crafter: found.items[5] if data storage pretty_crafter: _{firework:"minecraft:green_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 3887386
execute if data storage pretty_crafter: found.items[5] if data storage pretty_crafter: _{firework:"minecraft:red_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 11743532
execute if data storage pretty_crafter: found.items[5] if data storage pretty_crafter: _{firework:"minecraft:black_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 1973019

execute if data storage pretty_crafter: found.items[6] run data modify storage pretty_crafter: _.firework set from storage pretty_crafter: found.items[6].id
execute if data storage pretty_crafter: found.items[6] if data storage pretty_crafter: _{firework:"minecraft:white_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 15790320
execute if data storage pretty_crafter: found.items[6] if data storage pretty_crafter: _{firework:"minecraft:orange_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 15435844
execute if data storage pretty_crafter: found.items[6] if data storage pretty_crafter: _{firework:"minecraft:magenta_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 12801229
execute if data storage pretty_crafter: found.items[6] if data storage pretty_crafter: _{firework:"minecraft:light_blue_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 6719955
execute if data storage pretty_crafter: found.items[6] if data storage pretty_crafter: _{firework:"minecraft:yellow_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 14602026
execute if data storage pretty_crafter: found.items[6] if data storage pretty_crafter: _{firework:"minecraft:lime_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 4312372
execute if data storage pretty_crafter: found.items[6] if data storage pretty_crafter: _{firework:"minecraft:pink_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 14188952
execute if data storage pretty_crafter: found.items[6] if data storage pretty_crafter: _{firework:"minecraft:gray_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 4408131
execute if data storage pretty_crafter: found.items[6] if data storage pretty_crafter: _{firework:"minecraft:light_gray_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 11250603
execute if data storage pretty_crafter: found.items[6] if data storage pretty_crafter: _{firework:"minecraft:cyan_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 2651799
execute if data storage pretty_crafter: found.items[6] if data storage pretty_crafter: _{firework:"minecraft:purple_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 8073150
execute if data storage pretty_crafter: found.items[6] if data storage pretty_crafter: _{firework:"minecraft:blue_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 2437522
execute if data storage pretty_crafter: found.items[6] if data storage pretty_crafter: _{firework:"minecraft:brown_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 5320730
execute if data storage pretty_crafter: found.items[6] if data storage pretty_crafter: _{firework:"minecraft:green_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 3887386
execute if data storage pretty_crafter: found.items[6] if data storage pretty_crafter: _{firework:"minecraft:red_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 11743532
execute if data storage pretty_crafter: found.items[6] if data storage pretty_crafter: _{firework:"minecraft:black_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 1973019

execute if data storage pretty_crafter: found.items[7] run data modify storage pretty_crafter: _.firework set from storage pretty_crafter: found.items[7].id
execute if data storage pretty_crafter: found.items[7] if data storage pretty_crafter: _{firework:"minecraft:white_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 15790320
execute if data storage pretty_crafter: found.items[7] if data storage pretty_crafter: _{firework:"minecraft:orange_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 15435844
execute if data storage pretty_crafter: found.items[7] if data storage pretty_crafter: _{firework:"minecraft:magenta_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 12801229
execute if data storage pretty_crafter: found.items[7] if data storage pretty_crafter: _{firework:"minecraft:light_blue_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 6719955
execute if data storage pretty_crafter: found.items[7] if data storage pretty_crafter: _{firework:"minecraft:yellow_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 14602026
execute if data storage pretty_crafter: found.items[7] if data storage pretty_crafter: _{firework:"minecraft:lime_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 4312372
execute if data storage pretty_crafter: found.items[7] if data storage pretty_crafter: _{firework:"minecraft:pink_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 14188952
execute if data storage pretty_crafter: found.items[7] if data storage pretty_crafter: _{firework:"minecraft:gray_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 4408131
execute if data storage pretty_crafter: found.items[7] if data storage pretty_crafter: _{firework:"minecraft:light_gray_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 11250603
execute if data storage pretty_crafter: found.items[7] if data storage pretty_crafter: _{firework:"minecraft:cyan_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 2651799
execute if data storage pretty_crafter: found.items[7] if data storage pretty_crafter: _{firework:"minecraft:purple_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 8073150
execute if data storage pretty_crafter: found.items[7] if data storage pretty_crafter: _{firework:"minecraft:blue_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 2437522
execute if data storage pretty_crafter: found.items[7] if data storage pretty_crafter: _{firework:"minecraft:brown_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 5320730
execute if data storage pretty_crafter: found.items[7] if data storage pretty_crafter: _{firework:"minecraft:green_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 3887386
execute if data storage pretty_crafter: found.items[7] if data storage pretty_crafter: _{firework:"minecraft:red_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 11743532
execute if data storage pretty_crafter: found.items[7] if data storage pretty_crafter: _{firework:"minecraft:black_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 1973019

execute if data storage pretty_crafter: found.items[8] run data modify storage pretty_crafter: _.firework set from storage pretty_crafter: found.items[8].id
execute if data storage pretty_crafter: found.items[8] if data storage pretty_crafter: _{firework:"minecraft:white_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 15790320
execute if data storage pretty_crafter: found.items[8] if data storage pretty_crafter: _{firework:"minecraft:orange_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 15435844
execute if data storage pretty_crafter: found.items[8] if data storage pretty_crafter: _{firework:"minecraft:magenta_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 12801229
execute if data storage pretty_crafter: found.items[8] if data storage pretty_crafter: _{firework:"minecraft:light_blue_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 6719955
execute if data storage pretty_crafter: found.items[8] if data storage pretty_crafter: _{firework:"minecraft:yellow_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 14602026
execute if data storage pretty_crafter: found.items[8] if data storage pretty_crafter: _{firework:"minecraft:lime_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 4312372
execute if data storage pretty_crafter: found.items[8] if data storage pretty_crafter: _{firework:"minecraft:pink_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 14188952
execute if data storage pretty_crafter: found.items[8] if data storage pretty_crafter: _{firework:"minecraft:gray_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 4408131
execute if data storage pretty_crafter: found.items[8] if data storage pretty_crafter: _{firework:"minecraft:light_gray_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 11250603
execute if data storage pretty_crafter: found.items[8] if data storage pretty_crafter: _{firework:"minecraft:cyan_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 2651799
execute if data storage pretty_crafter: found.items[8] if data storage pretty_crafter: _{firework:"minecraft:purple_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 8073150
execute if data storage pretty_crafter: found.items[8] if data storage pretty_crafter: _{firework:"minecraft:blue_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 2437522
execute if data storage pretty_crafter: found.items[8] if data storage pretty_crafter: _{firework:"minecraft:brown_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 5320730
execute if data storage pretty_crafter: found.items[8] if data storage pretty_crafter: _{firework:"minecraft:green_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 3887386
execute if data storage pretty_crafter: found.items[8] if data storage pretty_crafter: _{firework:"minecraft:red_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 11743532
execute if data storage pretty_crafter: found.items[8] if data storage pretty_crafter: _{firework:"minecraft:black_dye"} run data modify storage pretty_crafter: found.recipe.result.tag.Explosion.FadeColors append value 1973019
